# Topic modeling
En este notebook se va a demostrar el uso de distintos modelos de extracción de temáticas (*topic modeling*) en un conjunto de textos de ejemplo sencillo (sin Deep Learning, para comprender sus limitaciones).

In [1]:
!pip install textacy

Collecting textacy
  Downloading textacy-0.13.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: cachetools>=4.0.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (5.5.1)
Requirement already satisfied: catalogue~=2.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (2.0.10)
Collecting cytoolz>=0.10.1 (from textacy)
  Downloading cytoolz-1.1.0-cp313-cp313-win_amd64.whl.metadata (5.3 kB)
Collecting floret~=0.10.0 (from textacy)
  Downloading floret-0.10.5.tar.gz (70 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: jellyfish>=0.8.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (1.2.1)
Requirement already satisfied: joblib>=0.13.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (1.5.2)
Requirement already satisfied: networkx>=2.7 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (3.5)
Requirement already satisfied: numpy>=1.17.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (2.3.5)
Collecting pyphen>=0.10.0 (from textacy)
  Downloading pyphen-0.17.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: requests>=2.10.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (2.32.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (1.7.2)
Requirement already satisfied: spacy~=3.0 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (3.8.14)
Requirement already satisfied: tqdm>=4.19.6 in c:\users\joanm\anaconda3\lib\site-packages (from textacy) (4.67.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (2.5.3)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (0.17.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (2.12.4)
Requirement already satisfied: jinja2 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\joanm\anaconda3\lib\site-packages (from spacy~=3.0->textacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\joanm\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy~=3.0->textacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\joanm\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy~=3.0->textacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\joanm\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy~=3.0->textacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\joanm\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy~=3.0->textacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\joanm\anaconda3\lib\site-packages (from requests>=2.10.0->textacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\joanm\anaconda3\lib\site-packages (from requests>=2.10.0->textacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\joanm\anaconda3\lib\site-packages (from requests>=2.10.0->textacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\joanm\anaconda3\lib\site-packages (from requests>=2.10.0->textacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\joanm\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy~=3.0->textacy) (1.3.3)
Requirement already satisfied: colorama in c:\users\joanm\anaconda3\lib\site-packages (from tqdm>=4.19.6->textacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\joanm\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\joanm\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\joanm\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (14.2.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\users\joanm\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\joanm\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (7.5.1)
Requirement already satisfied: httpx>=0.24.0 in c:\users\joanm\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (0.28.1)
Requirement already satisfied: toolz>=0.8.0 in c:\users\joanm\anaconda3\lib\site-packages (from cytoolz>=0.10.1->textacy) (1.0.0)
Requirement already satisfied: anyio in c:\users\joanm\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (4.10.0)
Requirement already satisfied: httpcore==1.* in c:\users\joanm\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\joanm\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\joanm\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\joanm\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\joanm\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (0.1.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\joanm\anaconda3\lib\site-packages (from scikit-learn>=1.0->textacy) (3.5.0)
Requirement already satisfied: wrapt in c:\users\joanm\anaconda3\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\joanm\anaconda3\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy~=3.0->textacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\joanm\anaconda3\lib\site-packages (from jinja2->spacy~=3.0->textacy) (3.0.2)
Downloading textacy-0.13.0-py3-none-any.whl (210 kB)
Downloading cytoolz-1.1.0-cp313-cp313-win_amd64.whl (946 kB)
   ---------------------------------------- 0.0/946.5 kB ? eta -:--:--
   ---------------------------------------- 946.5/946.5 kB 6.4 MB/s  0:00:00
Downloading pyphen-0.17.2-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----------------------------------- ---- 1.8/2.1 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 10.0 MB/s  0:00:00
Building wheels for collected packages: floret
  Building wheel for floret (pyproject.toml): started
  Building wheel for floret (pyproject.toml): finished with status 'error'
Failed to build floret

  error: subprocess-exited-with-error

  × Building wheel for floret (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      C:\Users\joanm\AppData\Local\Temp\pip-build-env-hena3x_o\overlay\Lib\site-packages\setuptools\dist.py:765: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: MIT License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\floret
      copying python\floret_module\floret\floret.py -> build\lib.win-amd64-cpython-313\floret
      copying python\floret_module\floret\__init__.py -> build\lib.win-amd64-cpython-313\floret
      creating build\lib.win-amd64-cpython-313\floret\util
      copying python\floret_module\floret\util\util.py -> build\lib.win-amd64-cpython-313\floret\util
      copying python\floret_module\floret\util\__init__.py -> build\lib.win-amd64-cpython-313\floret\util
      creating build\lib.win-amd64-cpython-313\floret\tests
      copying python\floret_module\floret\tests\test_configurations.py -> build\lib.win-amd64-cpython-313\floret\tests
      copying python\floret_module\floret\tests\test_script.py -> build\lib.win-amd64-cpython-313\floret\tests
      copying python\floret_module\floret\tests\test_tokenize.py -> build\lib.win-amd64-cpython-313\floret\tests
      copying python\floret_module\floret\tests\test_train.py -> build\lib.win-amd64-cpython-313\floret\tests
      copying python\floret_module\floret\tests\__init__.py -> build\lib.win-amd64-cpython-313\floret\tests
      copying python\floret_module\floret\tests\data.txt -> build\lib.win-amd64-cpython-313\floret\tests
      copying python\floret_module\floret\tests\README.md -> build\lib.win-amd64-cpython-313\floret\tests
      running build_ext
      building 'floret_pybind' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for floret
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> floret

In [ ]:
!pip install textacy
!python -m spacy download en_core_web_md

Collecting textacy
  Downloading textacy-0.13.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: cachetools>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (5.5.2)
Requirement already satisfied: catalogue~=2.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (2.0.10)
Collecting cytoolz>=0.10.1 (from textacy)
  Downloading cytoolz-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Collecting floret~=0.10.0 (from textacy)
  Downloading floret-0.10.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.1 kB)
Collecting jellyfish>=0.8.0 (from textacy)
  Downloading jellyfish-1.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.6 kB)
Requirement already satisfied: joblib>=0.13.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (1.4.2)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.11/dist-packages (from textacy) (3.4.2)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (2.0.2)
Collecting pyphen>=0.10.0 (from textacy)
  Downloading pyphen-0.17.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (2.32.3)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (1.15.2)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (1.6.1)
Requirement already satisfied: spacy~=3.0 in /usr/local/lib/python3.11/dist-packages (from textacy) (3.8.5)
Requirement already satisfied: tqdm>=4.19.6 in /usr/local/lib/python3.11/dist-packages (from textacy) (4.67.1)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from cytoolz>=0.10.1->textacy) (0.12.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->textacy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->textacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->textacy) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.10.0->textacy) (2025.4.26)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->textacy) (3.6.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (2.5.1)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (0.15.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (2.11.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy~=3.0->textacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy~=3.0->textacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy~=3.0->textacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy~=3.0->textacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy~=3.0->textacy) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy~=3.0->textacy) (0.4.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy~=3.0->textacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy~=3.0->textacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy~=3.0->textacy) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy~=3.0->textacy) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy~=3.0->textacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy~=3.0->textacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (2.19.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy~=3.0->textacy) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy~=3.0->textacy) (0.1.2)
Downloading textacy-0.13.0-py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 2.0 MB/s eta 0:00:00
Downloading cytoolz-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 33.0 MB/s eta 0:00:00
Downloading floret-0.10.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (321 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 321.6/321.6 kB 12.6 MB/s eta 0:00:00
Downloading jellyfish-1.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (356 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 356.9/356.9 kB 11.6 MB/s eta 0:00:00
Downloading pyphen-0.17.2-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 29.6 MB/s eta 0:00:00
Installing collected packages: pyphen, jellyfish, floret, cytoolz, textacy
Successfully installed cytoolz-1.0.1 floret-0.10.5 jellyfish-1.2.0 pyphen-0.17.2 textacy-0.13.0
Collecting en-core-web-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 15.1 MB/s eta 0:00:00

In [1]:
import spacy
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

nlp=spacy.load('es_core_news_md')

### Creación del corpus
Creamos un pequeño Corpus de ejemplo formado por 8 frases cortas. Definimos una sencilla función de normalización y aplicamos esta normalización a todo el corpus.

In [ ]:
import pandas as pd
import spacy

def extract_lemmas(doc):
    """Filtra y lematiza un documento ya procesado por spaCy."""
    return ' '.join(t.lemma_ for t in doc if not (t.is_punct or t.is_space or t.is_stop))

df = pd.read_csv('datos_clean.csv')

norm_corpus = list(map(extract_lemmas, nlp.pipe(df['texto'], batch_size=256,n_process=-1)))

## Topic modeling usando Scikit-learn
La librería `scikit-learn` implementa los modelos *Latent Semantic Analysis* (LSA) y *Latent Dirichlet Allocation* (LDA).  
Partimos de un modelo TF-IDF para el modelado LSA y de un modelo BoW para el modelado LDA

### Modelo LSA

In [5]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# usamos características tf-idf para LSA.
tfidf_vectorizer = TfidfVectorizer(min_df=2)
tfidf = tfidf_vectorizer.fit_transform(norm_corpus)

Definimos una función de ayuda para mostrar los resultados (términos asociados a cada tema)

In [7]:
def print_top_words(model, feature_names, n_top_words):
    """Función auxiliar para mostrar los términos más importantes
    de cada topic"""
    for topic_idx, topic in enumerate(model.components_):
        message = f"Topic #{topic_idx}: "
        message += " ".join([feature_names[i]
                             for i in topic.argsort()[:-n_top_words - 1:-1]])  # construye el texto con las palabras más importantes del topic
        print(message)
    print()

Calculamos los modelos para nuestro corpus (método `fit`) y vemos cuáles son los 3 términos con más peso para cada *topic*. Cada modelo asigna un grado de pertenencia en cada tema a cada término del vocabulario de la matriz tfidf o bow utilizada como entrada.

In [10]:
from sklearn.decomposition import TruncatedSVD, LatentDirichletAllocation

# Ajustamos el modelo LSA
lsa = TruncatedSVD(n_components=2).fit(tfidf)

print("\nTopics en modelo LSA:")
tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()
print(tfidf_feature_names)
print_top_words(lsa, tfidf_feature_names, 3)

Topics en modelo LSA:
['dog' 'fox' 'java' 'language' 'programming' 'python']
Topic #0: fox dog java
Topic #1: programming java language

In [11]:
for topic_idx, topic in enumerate(lsa.components_):
    print(f"\nTopic #{topic_idx}")
    for i, weight in enumerate(topic):
        print(f"{tfidf_feature_names[i]}: {weight:.3f}")

Topic #0
dog: 0.707
fox: 0.707
java: 0.000
language: -0.000
programming: -0.000
python: -0.000

Topic #1
dog: -0.000
fox: 0.000
java: 0.500
language: 0.500
programming: 0.500
python: 0.500

El método `fit` aprende la matriz de `topics` x `términos` para el corpus dado

In [12]:
lsa.components_.shape

(2, 6)

In [13]:
pd.DataFrame(np.round(lsa.components_, 4), columns=tfidf_feature_names)

      dog     fox  java  language  programming  python
0  0.7071  0.7071   0.0      -0.0         -0.0    -0.0
1 -0.0000  0.0000   0.5       0.5          0.5     0.5

Podemos ver el porcentaje de pertenencia a cada *topic* de cada una de los documentos asignados por el modelo con el método `transform`:

In [14]:
lsa.transform(tfidf)

array([[ 1.00000000e+00,  1.66533454e-16],
       [ 7.07106781e-01,  2.35513869e-16],
       [ 7.07106781e-01,  0.00000000e+00],
       [ 1.00000000e+00,  1.66533454e-16],
       [-1.92296269e-16,  8.66025404e-01],
       [-1.28197512e-16,  8.66025404e-01],
       [-1.66533454e-16,  1.00000000e+00],
       [-7.85046229e-17,  7.07106781e-01]])

In [16]:
np.round(lsa.transform(tfidf), 4)

array([[ 1.    ,  0.    ],
       [ 0.7071,  0.    ],
       [ 0.7071,  0.    ],
       [ 1.    ,  0.    ],
       [-0.    ,  0.866 ],
       [-0.    ,  0.866 ],
       [-0.    ,  1.    ],
       [-0.    ,  0.7071]])

Cada fila corresponde a un documento del Corpus, y cada columna el grado de pertenencia a ese tema del documento.  
El modelo ha separado correctamente el corpus en las dos temáticas principales:

In [17]:
np.argmax(lsa.transform(tfidf), axis=1)

array([0, 0, 0, 0, 1, 1, 1, 1])

### Modelo LDA

In [19]:
# usamos características BoW para LDA.
tf_vectorizer = CountVectorizer(min_df=2)
tf = tf_vectorizer.fit_transform(norm_corpus)

In [20]:
# Ajustamos el modelo LDA
lda = LatentDirichletAllocation(n_components=2, max_iter=5,
                                learning_method='batch',
                                learning_offset=50.,
                                random_state=0).fit(tf)

print("\nTopics en modelo LDA:")
tf_feature_names = tf_vectorizer.get_feature_names_out()
print_top_words(lda, tf_feature_names, 3)

Topics en modelo LDA:
Topic #0: dog fox java
Topic #1: programming language python

El atributo `components_` contiene los parámetros de la distribución de términos en *topics*.

In [ ]:
lda.components_.shape

(2, 6)

In [21]:
pd.DataFrame(lda.components_, columns=tfidf_feature_names)

        dog       fox      java  language  programming    python
0  3.491959  3.491955  0.513787  0.511393     0.511393  0.513756
1  0.508041  0.508045  3.486213  3.488607     3.488607  3.486244

Normalizando esta matriz muestra la distribución de términos dentro de cada *topic*

In [22]:
distribucion = lda.components_ / lda.components_.sum(axis=1)[:, np.newaxis]
pd.DataFrame(distribucion, columns=tfidf_feature_names)

        dog       fox      java  language  programming    python
0  0.386525  0.386524  0.056871  0.056606     0.056606  0.056868
1  0.033947  0.033947  0.232946  0.233106     0.233106  0.232948

Como en el caso del LSA, podemos ver el grado de pertenencia de cada documento a cada *topic*

In [23]:
lda.transform(tf)

array([[0.8319788 , 0.1680212 ],
       [0.74801655, 0.25198345],
       [0.74801659, 0.25198341],
       [0.8319788 , 0.1680212 ],
       [0.1281347 , 0.8718653 ],
       [0.12813488, 0.87186512],
       [0.1025063 , 0.8974937 ],
       [0.17085046, 0.82914954]])

In [ ]:
np.argmax(lda.transform(tf), axis=1)

array([0, 0, 0, 0, 1, 1, 1, 1])